{{ $portMap := dict "http" 8545 "ws" 8546 "rpc" 8551 }}
{{- range $chain := .Values.chains }}
{{- if hasPrefix "ethereum-execution" $chain.name }}
{{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}

{{ $chain := include "devnet.fullchain" (dict "name" $chain.id "file" $defaultFile "context" $) | fromJson }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chain.name }}-{{ $chain.id }}
  labels:
    app.kubernetes.io/name: {{ $chain.name }}-{{ $chain.id }}
spec:
  clusterIP: None
  ports:
    {{- range $name, $port := $portMap }}
    - name: {{ $name }}
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $port }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ $chain.name }}-{{ $chain.id }}
---
{{- end }}
{{- end }}
